In [1]:
# Importing necessary libraries
import pandas as pd

In [2]:
# Loading Dataset
movies = pd.read_csv(filepath_or_buffer="../data/movies.csv").loc[:, ["original_title", "overview"]]
movies.head()

,original_title,overview
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."

In [3]:
# Preprocessing 1 - Lowercasing
movies['overview'] = movies['overview'].str.lower()
movies.head()

,original_title,overview
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,Spectre,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,"john carter is a war-weary, former military ca..."

In [4]:
# Preprocessing 2 - Removing HTML Tags
import re

# Incase there are null values
movies.dropna(inplace=True)

def remove_html_tags(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r'', text)

movies['overview'] = movies['overview'].apply(remove_html_tags)
movies.sample(5)

,original_title,overview
1889,He Got Game,a basketball player's father must try to convi...
2059,Molière,"molière, a down-and-out actor-cum-playwright u..."
1827,Teenage Mutant Ninja Turtles II: The Secret of...,the turtles and the shredder battle once again...
79,Iron Man 2,with the world now aware of his dual life as t...
3611,A Farewell to Arms,british nurse catherine barkley (helen hayes) ...

In [5]:
# Preprocessing 3 - Removing Links
def removing_links(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')

    # This pattern is useful to filterout all types of links
    '''
        text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
        text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'
        text3 = 'Google search here www.google.com'
        text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'
    '''

    return pattern.sub(r'', text)

movies['overview'] = movies['overview'].apply(removing_links)
movies.sample(5)

,original_title,overview
3346,Jumping the Broom,two very different families converge on martha...
3276,It's Kind of a Funny Story,a clinically depressed teenager gets a new sta...
2643,Возвращение,a story of two russian boys whose father sudde...
2626,Idle Hands,anton is a cheerful but exceedingly non-ambiti...
366,Hollow Man,"cocky researcher, sebastian caine is working o..."

In [6]:
from urlextract import URLExtract # Incase you have'nt installed - !pip install urlextract

extractor = URLExtract()
urls = extractor.find_urls("Let's have URL www.stackoverflow.com as an example.")
print(urls) # prints: ['stackoverflow.com']

['www.stackoverflow.com']

In [7]:
# Preprocessing 4 - Remove Punctuations
import string
exclude = string.punctuation
print(exclude)

def remove_punctuation(overview):
    return "".join([(t if t not in exclude else "") for t in overview])
    # return text.translate(str.maketrans('', '', exclude)) - maketrans is a mapping function

movies['overview'] = movies['overview'].apply(remove_punctuation)
movies.sample(5)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

     original_title                                           overview
4612        Old Joy  two old pals reunite for a camping trip in ore...
2907   Pet Sematary  dr louis creeds family moves into the country ...
4314      Crowsnest  in late summer of 2011 five young friends on a...
3391  Dom Hemingway  after spending 12 years in prison for keeping ...
4375       Blue Car  gifted 18yearold meg has been abandoned by her...

In [8]:
# Preprocessing 5 - Chat Words Treatment
import json

with open(file="../data/chat_words_dictonary.json") as f:
    chat_words = json.load(f)

for index, (key, value) in enumerate(chat_words.items()):
    if index == 10: break
    print(f"{key} : {value}")

atm : at this moment
brb : be right back
lol : laughing out loud
btw : by the way
g2g : got to go
idk : I don't know
ikr : I know, right
np : no problem
omg : oh my god
rofl : rolling on floor laughing

In [9]:
def chat_words_treatment(text):
    return " ".join(list(map(lambda t: t if t not in chat_words else chat_words[t], text.split(" "))))

movies['overview'] = movies['overview'].apply(chat_words_treatment)
movies.sample(5)

        original_title                                           overview
2431  My Life in Ruins  a greek tour guide named georgia attempts to r...
3689           All Hat  an excon returns to his rural ontario roots an...
3226   Namastey London  indianborn manmohan malhotra decided to reloca...
1135       Lord of War  yuri orlov is a globetrotting arms dealer and ...
1242       The Reaping  katherine morrissey a former christian mission...

In [ ]:
# Preprocessing 6 - Spelling Correction
from textblob import TextBlob

def spelling_correction(text):

    textBlb = TextBlob(text) # Creating TextBlob object
    return textBlb.correct().string # Correcting spelling

spelling_correction("Hellow myi nmame ins dexter morgan")
# Note: Even for small datasets it takes lot of time

In [ ]:
# Preprocessing 7 - Removing Stop-Words
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stopwords = stopwords.words('english')

def remove_stopwords(text):
    result = []
    for word in text.split(" "):
        if word not in stopwords:
            result.append(word)
    return " ".join(result)

movies['Description'] = movies['Description'].apply(remove_stopwords)

In [15]:
# Preprocessing 8 - Removing Emojis
def remove_emoji(text):
    emoji_pattern = re.compile("["
            u"\U0001F600-\U0001F64F"  # emoticons
            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
            u"\U0001F680-\U0001F6FF"  # transport & map symbols
            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
            u"\U00002702-\U000027B0"
            u"\U000024C2-\U0001F251"
        "]+", 
        flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

remove_emoji("Loved the movie. It was 😘😘")

# movies['Description'] = movies['Description'].apply(remove_emoji)

'Loved the movie. It was '

In [ ]:
# Preprocessing 8' - Replacing emojis with there english representation
import emoji

print(emoji.demojize('Python is 🔥'))
print(emoji.demojize('Loved the movie. It was 😘'))
print(emoji.demojize('Loved the movie. It was 😂'))

Python is :fire:
Loved the movie. It was :face_blowing_a_kiss:
Loved the movie. It was :face_with_tears_of_joy:

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize, sent_tokenize
tokens = word_tokenize("".join(movies['Description']))

In [ ]:
tokens[:5]

['imprisoned', '1940s', 'double', 'murder', 'wife']

In [ ]:
movies.loc[0, 'Description']

'imprisoned 1940s double murder wife lover upstanding banker andy dufresne begins new life shawshank prison puts accounting skills work amoral warden long stretch prison dufresne comes admired inmates including older prisoner named red integrity unquenchable sense hope'

In [ ]:
sentences_tokens = sent_tokenize("".join(movies['Description']))
# Since we removed all the puncuations we got only one token

In [ ]:
sent_tokenize("Hello my name is Dexter. I live at Kolhapur")

['Hello my name is Dexter.', 'I live at Kolhapur']

In [ ]:
import spacy

# Creating blank language object then
# tokenizing words of the sentence
nlp = spacy.blank("en")

doc = nlp("am am are are")
doc

am am are are

In [ ]:
tokens = sent_tokenize("$10 15km 15-20 U.S.")
doc = nlp("$10 15km 15-20 U.S.")

print(tokens)

['$10 15km 15-20 U.S.']

In [ ]:
doc

$10 15km 15-20 U.S.

## Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download WordNet and punkt if you haven't already
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
# Initialize the lemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

# Sample sentence
sentence = "He was running and eating at the same time. He has a bad habit of swimming after playing long hours in the Sun."

# Tokenize the sentence into words
words = word_tokenize(sentence)

# Lemmatize each word in the sentence with 'v' as the POS tag for verbs
lemmatized_words = [wordnet_lemmatizer.lemmatize(word, pos='v') for word in words]

# Join the lemmatized words back into a sentence
lemmatized_sentence = ' '.join(lemmatized_words)

print(lemmatized_sentence)

He be run and eat at the same time . He have a bad habit of swim after play long hours in the Sun .

# Text Representation

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase = True, stop_words = 'english', analyzer = 'word', ngram_range = (1, 3), binary = False)
bow = cv.fit_transform(movies['Description'])

In [ ]:
cv.vocabulary_

{'imprisoned': 191271,
 '1940s': 1389,
 'double': 108876,
 'murder': 258961,
 'wife': 422043,
 'lover': 233240,
 'upstanding': 407478,
 'banker': 30302,
 'andy': 16886,
 'dufresne': 112313,
 'begins': 34362,
 'new': 265888,
 'life': 221885,
 'shawshank': 344919,
 'prison': 299946,
 'puts': 305621,
 'accounting': 6273,
 'skills': 350555,
 'work': 427250,
 'amoral': 16173,
 'warden': 416720,
 'long': 229465,
 'stretch': 367680,
 'comes': 71461,
 'admired': 8057,
 'inmates': 194183,
 'including': 191776,
 'older': 274225,
 'prisoner': 300287,
 'named': 262081,
 'red': 313608,
 'integrity': 195676,
 'unquenchable': 406258,
 'sense': 340372,
 'hope': 183544,
 'imprisoned 1940s': 191274,
 '1940s double': 1392,
 'double murder': 108913,
 'murder wife': 259355,
 'wife lover': 422494,
 'lover upstanding': 233339,
 'upstanding banker': 407479,
 'banker andy': 30305,
 'andy dufresne': 16898,
 'dufresne begins': 112314,
 'begins new': 34645,
 'new life': 266617,
 'life shawshank': 223525,
 'shawshank prison': 344920,
 'prison puts': 300199,
 'puts accounting': 305622,
 'accounting skills': 6274,
 'skills work': 350667,
 'work amoral': 427276,
 'amoral warden': 16176,
 'warden long': 416727,
 'long stretch': 229677,
 'stretch prison': 367692,
 'prison dufresne': 300044,
 'dufresne comes': 112316,
 'comes admired': 71464,
 'admired inmates': 8058,
 'inmates including': 194194,
 'including older': 191903,
 'older prisoner': 274309,
 'prisoner named': 300328,
 'named red': 262557,
 'red integrity': 313650,
 'integrity unquenchable': 195684,
 'unquenchable sense': 406259,
 'sense hope': 340400,
 'imprisoned 1940s double': 191275,
 '1940s double murder': 1393,
 'double murder wife': 108914,
 'murder wife lover': 259358,
 'wife lover upstanding': 422496,
 'lover upstanding banker': 233340,
 'upstanding banker andy': 407480,
 'banker andy dufresne': 30306,
 'andy dufresne begins': 16899,
 'dufresne begins new': 112315,
 'begins new life': 34646,
 'new life shawshank': 266654,
 'life shawshank prison': 223526,
 'shawshank prison puts': 344921,
 'prison puts accounting': 300200,
 'puts accounting skills': 305623,
 'accounting skills work': 6275,
 'skills work amoral': 350668,
 'work amoral warden': 427277,
 'amoral warden long': 16177,
 'warden long stretch': 416728,
 'long stretch prison': 229678,
 'stretch prison dufresne': 367693,
 'prison dufresne comes': 300045,
 'dufresne comes admired': 112317,
 'comes admired inmates': 71465,
 'admired inmates including': 8059,
 'inmates including older': 194195,
 'including older prisoner': 191904,
 'older prisoner named': 274310,
 'prisoner named red': 300329,
 'named red integrity': 262558,
 'red integrity unquenchable': 313651,
 'integrity unquenchable sense': 195685,
 'unquenchable sense hope': 406260,
 'spanning': 357510,
 'years': 432154,
 '1945': 1491,
 '1955': 1616,
 'chronicle': 64272,
 'fictional': 139293,
 'italianamerican': 199974,
 'corleone': 78948,
 'crime': 83647,
 'family': 132758,
 'organized': 277028,
 'patriarch': 284452,
 'vito': 413699,
 'barely': 30715,
 'survives': 374499,
 'attempt': 25255,
 'youngest': 435594,
 'son': 354371,
 'michael': 249365,
 'steps': 363672,
 'care': 54105,
 'wouldbe': 430455,
 'killers': 210532,
 'launching': 216165,
 'campaign': 52434,
 'bloody': 40366,
 'revenge': 321930,
 'spanning years': 357525,
 'years 1945': 432155,
 '1945 1955': 1492,
 '1955 chronicle': 1617,
 'chronicle fictional': 64283,
 'fictional italianamerican': 139310,
 'italianamerican corleone': 199975,
 'corleone crime': 78953,
 'crime family': 83747,
 'family organized': 133692,
 'organized crime': 277031,
 'family patriarch': 133702,
 'patriarch vito': 284471,
 'vito corleone': 413700,
 'corleone barely': 78951,
 'barely survives': 30758,
 'survives attempt': 374500,
 'attempt life': 25355,
 'life youngest': 224000,
 'youngest son': 435616,
 'son michael': 354826,
 'michael steps': 249484,
 'steps care': 363681,
 'care wouldbe': 54217,
 'wouldbe killers': 430466,
 'killers launching': 210585,
 'launching campaign': 216166,
 'campaign bloody': 52441,
 'bloody revenge': 40433,
 'spanning years 1945': 357526,
 'years 1945 1955': 432156,
 '1945 1955 chronicle': 1493,
 '1955 chronicle fictional': 1618,
 'chronicle fictional italianamerican': 64284,
 'fictional italianamerican corleone': 139311,
 'italianamerican corleone crime': 199976,
 'corleone crime family': 78954,
 'crime family organized': 83752,
 'family organized crime': 133693,
 'organized crime family': 277034,
 'crime family patriarch': 83753,
 'family patriarch vito': 133705,
 'patriarch vito corleone': 284472,
 'vito corleone barely': 413701,
 'corleone barely survives': 78952,
 'barely survives attempt': 30759,
 'survives attempt life': 374501,
 'attempt life youngest': 25358,
 'life youngest son': 224001,
 'youngest son michael': 435620,
 'son michael steps': 354828,
 'michael steps care': 249485,
 'steps care wouldbe': 363682,
 'care wouldbe killers': 54218,
 'wouldbe killers launching': 430467,
 'killers launching campaign': 210586,
 'launching campaign bloody': 216167,
 'campaign bloody revenge': 52443,
 'continuing': 77167,
 'saga': 330766,
 'young': 433777,
 'grows': 168063,
 'sicily': 347629,
 '1910s': 1175,
 'york': 433235,
 '1950s': 1551,
 'attempts': 25576,
 'expand': 127720,
 'business': 50112,
 'las': 215319,
 'vegas': 409837,
 'hollywood': 181598,
 'cuba': 85689,
 'continuing saga': 77176,
 'saga corleone': 330773,
 'family young': 134203,
 'young vito': 435278,
 'corleone grows': 78955,
 'grows sicily': 168147,
 'sicily 1910s': 347630,
 '1910s new': 1176,
 'new york': 267303,
 'york 1950s': 433242,
 '1950s michael': 1586,
 'michael corleone': 249378,
 'corleone attempts': 78949,
 'attempts expand': 25639,
 'expand family': 127725,
 'family business': 132882,
 'business las': 50208,
 'las vegas': 215324,
 'vegas hollywood': 409872,
 'hollywood cuba': 181627,
 'continuing saga corleone': 77177,
 'saga corleone crime': 330774,
 'crime family young': 83754,
 'family young vito': 134206,
 'young vito corleone': 435279,
 'vito corleone grows': 413702,
 'corleone grows sicily': 78956,
 'grows sicily 1910s': 168148,
 'sicily 1910s new': 347631,
 '1910s new york': 1177,
 'new york 1950s': 267307,
 'york 1950s michael': 433243,
 '1950s michael corleone': 1587,
 'michael corleone attempts': 249379,
 'corleone attempts expand': 78950,
 'attempts expand family': 25640,
 'expand family business': 127726,
 'family business las': 132886,
 'business las vegas': 50209,
 'las vegas hollywood': 215338,
 'vegas hollywood cuba': 409873,
 'true': 397798,
 'story': 365413,
 'businessman': 50351,
 'oskar': 277615,
 'schindler': 334087,
 'saved': 333102,
 'thousand': 386417,
 'jewish': 202937,
 'lives': 226748,
 'nazis': 263987,
 'worked': 427757,
 'slaves': 351121,
 'factory': 131094,
 'world': 428452,
 'war': 415988,
 'ii': 189496,
 'true story': 398022,
 'story businessman': 365527,
 'businessman oskar': 50424,
 'oskar schindler': 277622,
 'schindler saved': 334088,
 'saved thousand': 333143,
 'thousand jewish': 386424,
 'jewish lives': 202986,
 'lives nazis': 227200,
 'nazis worked': 264017,
 'worked slaves': 427775,
 'slaves factory': 351124,
 'factory world': 131136,
 'world war': 429717,
 'war ii': 416264,
 'true story businessman': 398034,
 'story businessman oskar': 365528,
 'businessman oskar schindler': 50425,
 'oskar schindler saved': 277623,
 'schindler saved thousand': 334089,
 'saved thousand jewish': 333144,
 'thousand jewish lives': 386425,
 'jewish lives nazis': 202987,
 'lives nazis worked': 227201,
 'nazis worked slaves': 264018,
 'worked slaves factory': 427776,
 'slaves factory world': 351125,
 'factory world war': 131138,
 'world war ii': 429729,
 'defense': 96053,
 'prosecution': 302722,
 'rested': 319776,
 'jury': 207229,
 'filing': 140581,
 'room': 327242,
 'decide': 94204,
 'spanishamerican': 357501,
 'guilty': 168880,
 'innocent': 194342,
 'murdering': 259627,
 'father': 135926,
 'open': 275025,
 'shut': 347376,
 'case': 55460,
 'soon': 355385,
 'minidrama': 251403,
 'jurors': 207224,
 'prejudices': 297748,
 'preconceptions': 297406,
 'trial': 395754,
 'accused': 6326,
 'defense prosecution': 96092,
 'prosecution rested': 302727,
 'rested jury': 319777,
 'jury filing': 207240,
 'filing jury': 140584,
 'jury room': 207244,
 'room decide': 327269,
 'decide young': 94478,
 'young spanishamerican': 435148,
 'spanishamerican guilty': 357502,
 'guilty innocent': 168887,
 'innocent murdering': 194397,
 'murdering father': 259641,
 'father begins': 136000,
 'begins open': 34661,
 'open shut': 275107,
 'shut case': 347379,
 'case soon': 55674,
 'soon minidrama': 355880,
 'minidrama jurors': 251404,
 'jurors prejudices': 207227,
 'prejudices preconceptions': 297753,
 'preconceptions trial': 297408,
 'trial accused': 395757,
 'defense prosecution rested': 96093,
 'prosecution rested jury': 302728,
 'rested jury filing': 319778,
 'jury filing jury': 207241,
 'filing jury room': 140585,
 'jury room decide': 207245,
 'room decide young': 327270,
 'decide young spanishamerican': 94479,
 'young spanishamerican guilty': 435149,
 'spanishamerican guilty innocent': 357503,
 'guilty innocent murdering': 168888,
 'innocent murdering father': 194398,
 'murdering father begins': 259642,
 'father begins open': 136001,
 'begins open shut': 34662,
 'open shut case': 275108,
 'shut case soon': 347380,
 'case soon minidrama': 55676,
 'soon minidrama jurors': 355881,
 'minidrama jurors prejudices': 251405,
 'jurors prejudices preconceptions': 207228,
 'prejudices preconceptions trial': 297754,
 'preconceptions trial accused': 297409,
 'girl': 159976,
 'chihiro': 61994,
 'trapped': 394416,
 'strange': 366618,
 'spirits': 359003,
 'parents': 281248,
 'undergo': 403195,
 'mysterious': 260736,
 'transformation': 393912,
 'courage': 80948,
 'knew': 211941,
 'free': 150445,
 'young girl': 434333,
 'girl chihiro': 160080,
 'chihiro trapped': 61995,
 'trapped strange': 394574,
 'strange new': 366755,
 'new world': 267275,
 'world spirits': 429509,
 'spirits parents': 359041,
 'parents undergo': 281646,
 'undergo mysterious': 403202,
 'mysterious transformation': 261421,
 'transformation courage': 393921,
 'courage knew': 80989,
 'knew free': 211961,
 'free family': 150482,
 'young girl chihiro': 434342,
 'girl chihiro trapped': 160081,
 'chihiro trapped strange': 61996,
 'trapped strange new': 394575,
 'strange new world': 366759,
 'new world spirits': 267288,
 'world spirits parents': 429510,
 'spirits parents undergo': 359042,
 'parents undergo mysterious': 281647,
 'undergo mysterious transformation': 403203,
 'mysterious transformation courage': 261422,
 'transformation courage knew': 393922,
 'courage knew free': 80990,
 'knew free family': 211962,
 'raj': 308927,
 'rich': 322677,
 'carefree': 54549,
 'happygolucky': 171781,
 'second': 337213,
 'generation': 157487,
 'nri': 270793,
 'simran': 348656,
 'daughter': 89545,
 'chaudhary': 61156,
 'baldev': 29498,
 'singh': 348917,
 'spite': 359109,
 'strict': 367712,
 'adherence': 7963,
 'indian': 192500,
 'values': 409120,
 'left': 219720,
 'india': 192451,
 'married': 241950,
 'childhood': 62301,
 'fiancé': 139153,
 'leaves': 219000,
 'mission': 252503,
 'hands': 170710,
 'claim': 66045,
 'lady': 214033,
 'love': 232068,
 'noses': 270243,
 'raj rich': 308932,
 'rich carefree': 322698,
 'carefree happygolucky': 54557,
 'happygolucky second': 171790,
 'second generation': 337252,
 'generation nri': 157503,
 'nri simran': 270794,
 'simran daughter': 348657,
 'daughter chaudhary': 89650,
 'chaudhary baldev': 61157,
 'baldev singh': 29499,
 'singh spite': 348920,
 'spite nri': 359116,
 'nri strict': 270796,
 'strict adherence': 367713,
 'adherence indian': 7964,
 'indian values': 192539,
 'values simran': 409140,
 'simran left': 348659,
 'left india': 219917,
 'india married': 192470,
 'married childhood': 241988,
 'childhood fiancé': 62366,
 'fiancé raj': 139183,
 'raj leaves': 308928,
 'leaves india': 219089,
 'india mission': 192472,
 'mission hands': 252703,
 'hands claim': 170727,
 'claim lady': 66075,
 'lady love': 214078,
 'love noses': 232754,
 'noses family': 270244,
 'family begins': 132844,
 'begins saga': 34764,
 'raj rich carefree': 308933,
 'rich carefree happygolucky': 322699,
 'carefree happygolucky second': 54558,
 'happygolucky second generation': 171791,
 'second generation nri': 337253,
 'generation nri simran': 157504,
 'nri simran daughter': 270795,
 'simran daughter chaudhary': 348658,
 'daughter chaudhary baldev': 89651,
 'chaudhary baldev singh': 61158,
 'baldev singh spite': 29500,
 'singh spite nri': 348921,
 'spite nri strict': 359117,
 'nri strict adherence': 270797,
 'strict adherence indian': 367714,
 'adherence indian values': 7965,
 'indian values simran': 192540,
 'values simran left': 409141,
 'simran left india': 348660,
 'left india married': 219918,
 'india married childhood': 192471,
 'married childhood fiancé': 241989,
 'childhood fiancé raj': 62367,
 'fiancé raj leaves': 139184,
 'raj leaves india': 308929,
 'leaves india mission': 219090,
 'india mission hands': 192473,
 'mission hands claim': 252704,
 'hands claim lady': 170728,
 'claim lady love': 66076,
 'lady love noses': 214080,
 'love noses family': 232755,
 'noses family begins': 270245,
 'family begins saga': 132846,
 'batman': 31679,
 'raises': 308877,
 'stakes': 360563,
 'help': 175647,
 'lt': 233860,
 'jim': 203166,
 'gordon': 163983,
 'district': 106346,
 'attorney': 26078,
 'harvey': 172843,
 'dent': 97344,
 'sets': 342714,
 'dismantle': 105701,
 'remaining': 316469,
 'criminal': 84054,
 'organizations': 277009,
 'plague': 290713,
 'streets': 367417,
 'partnership': 282750,
 'proves': 303660,
 'effective': 115223,
 'prey': 299108,
 'reign': 314796,
 'chaos': 59857,
 'unleashed': 405606,
 'rising': 324161,
 'mastermind': 243482,
 'known': 212428,
 'terrified': 383088,
 'citizens': 65028,
 'gotham': 164205,
 'joker': 205278,
 'batman raises': 31717,
 'raises stakes': 308894,
 'stakes war': 360597,
 'war crime': 416108,
 'crime help': 83779,
 'help lt': 176125,
 'lt jim': 233880,
 'jim gordon': 203206,
 'gordon district': 163990,
 'district attorney': 106354,
 'attorney harvey': 26110,
 'harvey dent': 172858,
 'dent batman': 97345,
 'batman sets': 31724,
 'sets dismantle': 342782,
 'dismantle remaining': 105704,
 'remaining criminal': 316480,
 'criminal organizations': 84210,
 'organizations plague': 277012,
 'plague streets': 290741,
 'streets partnership': 367518,
 'partnership proves': 282777,
 'proves effective': 303672,
 'effective soon': 115232,
 'soon prey': 355936,
 'prey reign': 299138,
 'reign chaos': 314799,
 'chaos unleashed': 59953,
 'unleashed rising': 405619,
 'rising criminal': 324168,
 'criminal mastermind': 84177,
 'mastermind known': 243504,
 'known terrified': 212690,
 'terrified citizens': 383093,
 'citizens gotham': 65047,
 'gotham joker': 164228,
 'batman raises stakes': 31718,
 'raises stakes war': 308895,
 'stakes war crime': 360598,
 'war crime help': 416109,
 'crime help lt': 83780,
 'help lt jim': 176126,
 'lt jim gordon': 233881,
 'jim gordon district': 203207,
 'gordon district attorney': 163991,
 'district attorney harvey': 106356,
 'attorney harvey dent': 26111,
 'harvey dent batman': 172859,
 'dent batman sets': 97347,
 'batman sets dismantle': 31725,
 'sets dismantle remaining': 342783,
 'dismantle remaining criminal': 105705,
 'remaining criminal organizations': 316481,
 'criminal organizations plague': 84211,
 'organizations plague streets': 277013,
 'plague streets partnership': 290742,
 'streets partnership proves': 367519,
 'partnership proves effective': 282778,
 'proves effective soon': 303673,
 'effective soon prey': 115233,
 'soon prey reign': 355937,
 'prey reign chaos': 299139,
 'reign chaos unleashed': 314800,
 'chaos unleashed rising': 59954,
 'unleashed rising criminal': 405620,
 'rising criminal mastermind': 324169,
 'criminal mastermind known': 84181,
 'mastermind known terrified': 243507,
 'known terrified citizens': 212691,
 'terrified citizens gotham': 383094,
 'citizens gotham joker': 65048,
 'supernatural': 372733,
 'tale': 377880,
 'set': 342186,
 'death': 93038,
 'row': 327979,
 'southern': 356950,
 'gentle': 157807,
 'giant': 159411,
 'john': 204322,
 'coffey': 69347,
 'possesses': 295656,
 'power': 296314,
 'heal': 174088,
 'peoples': 286447,
 'ailments': 11842,
 'cell': 57762,
 'blocks': 40088,
 'head': 173572,
 'guard': 168376,
 'paul': 284682,
 'edgecomb': 114885,
 'recognizes': 312897,
 'coffeys': 69350,
 'miraculous': 251717,
 'gift': 159544,
 'tries': 396112,
 'desperately': 98805,
 'stave': 362812,
 'condemned': 74580,
 'mans': 240376,
 'execution': 126894,
 'supernatural tale': 372852,
 'tale set': 378008,
 'set death': 342320,
 'death row': 93470,
 'row southern': 327998,
 'southern prison': 357000,
 'prison gentle': 300091,
 'gentle giant': 157812,
 'giant john': 159443,
 'john coffey': 204367,
 'coffey possesses': 69348,
 'possesses mysterious': 295668,
 'mysterious power': 261282,
 'power heal': 296431,
 'heal peoples': 174099,
 'peoples ailments': 286448,
 'ailments cell': 11843,
 'cell blocks': 57765,
 'blocks head': 40093,
 'head guard': 173670,
 'guard paul': 168428,
 'paul edgecomb': 284723,
 'edgecomb recognizes': 114886,
 'recognizes coffeys': 312898,
 'coffeys miraculous': 69351,
 'miraculous gift': 251727,
 'gift tries': 159602,
 'tries desperately': 396189,
 'desperately help': 98819,
 'help stave': 176450,
 'stave condemned': 362815,
 'condemned mans': 74592,
 'mans execution': 240399,
 'supernatural tale set': 372853,
 'tale set death': 378009,
 'set death row': 342321,
 'death row southern': 93475,
 'row southern prison': 327999,
 'southern prison gentle': 357001,
 'prison gentle giant': 300092,
 'gentle giant john': 157813,
 'giant john coffey': 159444,
 'john coffey possesses': 204368,
 'coffey possesses mysterious': 69349,
 'possesses mysterious power': 295669,
 'mysterious power heal': 261285,
 'power heal peoples': 296433,
 'heal peoples ailments': 174100,
 'peoples ailments cell': 286449,
 'ailments cell blocks': 11844,
 'cell blocks head': 57766,
 'blocks head guard': 40094,
 'head guard paul': 173671,
 'guard paul edgecomb': 168430,
 'paul edgecomb recognizes': 284724,
 'edgecomb recognizes coffeys': 114887,
 'recognizes coffeys miraculous': 312899,
 'coffeys miraculous gift': 69352,
 'miraculous gift tries': 251728,
 'gift tries desperately': 159603,
 'tries desperately help': 396191,
 'desperately help stave': 98821,
 'help stave condemned': 176451,
 'stave condemned mans': 362816,
 'condemned mans execution': 74593,
 'unemployed': 403769,
 'kitaeks': 211778,
 'takes': 377004,
 'peculiar': 285509,
 'wealthy': 419082,
 'glamorous': 161712,
 'parks': 282193,
 'livelihood': 226708,
 'entangled': 121244,
 'unexpected': 403837,
 'incident': 191635,
 'unemployed kitaeks': 403794,
 'kitaeks family': 211779,
 'family takes': 134006,
 'takes peculiar': 377374,
 'peculiar wealthy': 285528,
 'wealthy glamorous': 419173,
 'glamorous parks': 161740,
 'parks livelihood': 282200,
 'livelihood entangled': 226709,
 'entangled unexpected': 121286,
 'unexpected incident': 403947,
 'unemployed kitaeks family': 403795,
 'kitaeks family takes': 211780,
 'family takes peculiar': 134008,
 'takes peculiar wealthy': 377375,
 'peculiar wealthy glamorous': 285529,
 'wealthy glamorous parks': 419175,
 'glamorous parks livelihood': 161741,
 'parks livelihood entangled': 282201,
 'livelihood entangled unexpected': 226710,
 'entangled unexpected incident': 121287,
 'burgerloving': 49738,
 'hit': 180468,
 'man': 238127,
 'philosophical': 288607,
 'partner': 282445,
 'drugaddled': 111885,
 'gangsters': 156470,
 'moll': 254143,
 'washedup': 417405,
 'boxer': 43595,
 'converge': 77705,
 'sprawling': 359553,
 'comedic': 71334,
 'caper': 53055,
 'adventures': 9053,
 'unfurl': 404532,
 'stories': 365141,
 'ingeniously': 193635,
 'trip': 396738,
 'forth': 148686,
 'time': 388078,
 'burgerloving hit': 49739,
 'hit man': 180538,

In [ ]:
len(cv.vocabulary_)

29874

In [ ]:
bow[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.feature_extraction.text import TfimoviesVectorizer

tfimovies = TfimoviesVectorizer()
encoded = tfimovies.fit_transform(movies['Description'])

In [ ]:
encoded[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
print(tfimovies.imovies_)

[9.08343148 9.48889659 8.3902843  ... 9.48889659 9.48889659 9.08343148]

array(['00', '006', '007', ..., 'éric', 'öztürk', 'ʻohana'], dtype=object)

# Deep Learning Approaches

In [ ]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim) (7.0.5)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open>=1.8.1->gensim) (1.16.0)

In [ ]:
from gensim.utils import simple_preprocess

In [ ]:
simple_preprocess("Hello My name is Harry")

['hello', 'my', 'name', 'is', 'harry']

In [ ]:
store = []
movies['Description'].apply(lambda x: store.append(simple_preprocess(x)))

0       None
1       None
2       None
3       None
4       None
        ...
9715    None
9716    None
9717    None
9718    None
9719    None
Name: Description, Length: 9720, dtype: object

In [ ]:
len(store)

9720

In [ ]:
import gensim
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    vector_size = 100
)

In [ ]:
model.build_vocab(store)

In [ ]:
model.epochs

5

In [ ]:
model.train(store, total_examples = model.corpus_count, epochs = model.epochs)

(1177118, 1261000)

In [ ]:
model.wv.most_similar('boy')

[('meets', 0.9993821382522583),
 ('son', 0.9993306994438171),
 ('mother', 0.9992178678512573),
 ('married', 0.9991076588630676),
 ('couple', 0.9990133047103882),
 ('beautiful', 0.9989761710166931),
 ('whose', 0.9989615678787231),
 ('father', 0.9989044070243835),
 ('daughter', 0.9989011883735657),
 ('teenage', 0.9988861083984375)]

In [ ]:
model.wv.doesnt_match(['boy', 'girl', 'man', 'women', 'merry'])

'merry'

In [ ]:
model.wv['king']

array([-4.7805241e-01,  8.9421040e-01,  5.9682089e-01,  4.0302407e-02,
       -1.8417187e-01, -1.0727488e+00,  3.2542974e-01,  1.6779027e+00,
       -3.6795244e-01, -2.4228179e-01, -3.5064438e-01, -1.4925445e+00,
       -1.0779732e-02,  3.4555501e-01,  5.9883475e-01, -1.2025588e+00,
        6.4149626e-02, -1.2701110e+00, -3.3447571e-02, -1.7758778e+00,
        4.0661937e-01,  5.2599221e-01,  5.1979232e-01, -2.7209094e-01,
       -3.7241276e-02, -1.4135563e-02, -6.5465808e-01, -4.3948710e-01,
       -9.2859024e-01, -1.2027569e-01,  5.4470801e-01,  1.1613366e-01,
        1.7044647e-03, -5.4109949e-01, -7.6100066e-02,  8.7756443e-01,
        3.2019526e-01, -6.0449409e-01, -3.3756110e-01, -1.6588789e+00,
       -4.8590802e-02, -7.6649451e-01, -4.9502033e-01,  1.7559346e-02,
        5.0756824e-01, -3.2639140e-01, -7.8039438e-01, -5.7014484e-02,
       -1.4682734e-01,  8.7216234e-01, -1.2324012e-01, -6.3025528e-01,
       -7.1349901e-01, -2.1083152e-01, -7.2468585e-01,  7.2306651e-04,
        8.2855749e-01,  1.6489227e-01, -6.3479984e-01,  5.6939644e-01,
        1.5093255e-01,  5.9575617e-01, -2.8173634e-01,  3.5469779e-01,
       -1.1669238e+00,  1.0447507e+00,  1.4123648e-02,  2.8364691e-01,
       -1.2597144e+00,  9.1548300e-01, -3.7771076e-01,  7.9905742e-01,
        1.1291913e+00, -3.1960827e-01,  6.3388723e-01,  6.4114755e-01,
        1.9523956e-02,  2.6556155e-01, -7.5256175e-01,  4.7439125e-01,
       -6.7207444e-01, -3.9780277e-01, -6.8112975e-01,  9.7163594e-01,
       -4.3031264e-02,  2.1179371e-01,  4.4791922e-02,  9.5825452e-01,
        9.5981377e-01,  4.0326133e-01,  6.3796276e-01,  2.9649687e-01,
        1.8611212e-01,  2.0980795e-01,  1.4815457e+00,  1.0264169e+00,
        8.1132370e-01, -1.0760025e+00,  2.0492871e-01,  1.3222277e-01],
      dtype=float32)

In [ ]:
model.wv.similarity('bottle','can')

0.99186695

In [ ]:
model.wv.get_normed_vectors() # Returns the vector representation of all the words

array([[-0.06355576,  0.13680956,  0.09171266, ..., -0.15839307,
         0.03032753,  0.01129388],
       [-0.08647829,  0.1175487 ,  0.10407068, ..., -0.14106596,
        -0.01215109, -0.0006144 ],
       [-0.05690471,  0.15416141,  0.07277973, ..., -0.15262741,
         0.0419447 ,  0.00231048],
       ...,
       [-0.12808035,  0.18103282,  0.08616749, ..., -0.18451056,
        -0.01988638,  0.00138477],
       [-0.12168589,  0.08864621,  0.03618131, ..., -0.11659244,
        -0.04106048,  0.08991076],
       [-0.09016749,  0.1173208 ,  0.0997637 , ..., -0.14454001,
         0.05217974, -0.01003663]], dtype=float32)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 3)

In [ ]:
pca.fit_transform(model.wv.get_normed_vectors())

array([[-0.03644544, -0.00485121, -0.03764542],
       [-0.00977886, -0.09970655, -0.10137251],
       [-0.02839023, -0.01952115, -0.08144549],
       ...,
       [ 0.03777266,  0.03631732,  0.04492512],
       [ 0.04612064,  0.02249181,  0.04885054],
       [-0.02260065,  0.03490208, -0.02947539]], dtype=float32)

In [ ]:
y = model.wv.index_to_key
y

['life',
 'new',
 'young',
 'one',
 'world',
 'family',
 'two',
 'must',
 'man',
 'find',
 'love',
 'years',
 'finds',
 'friends',
 'woman',
 'home',
 'help',
 'time',
 'back',
 'story',
 'school',
 'lives',
 'soon',
 'get',
 'take',
 'father',
 'group',
 'way',
 'mysterious',
 'war',
 'becomes',
 'wife',
 'town',
 'girl',
 'son',
 'three',
 'takes',
 'city',
 'together',
 'mother',
 'become',
 'first',
 'save',
 'daughter',
 'old',
 'friend',
 'make',
 'team',
 'begins',
 'day',
 'death',
 'discovers',
 'high',
 'secret',
 'police',
 'named',
 'best',
 'gets',
 'past',
 'boy',
 'former',
 'people',
 'set',
 'meets',
 'hes',
 'small',
 'go',
 'forced',
 'york',
 'house',
 'however',
 'american',
 'true',
 'order',
 'mission',
 'night',
 'discover',
 'goes',
 'job',
 'living',
 'falls',
 'work',
 'murder',
 'evil',
 'fight',
 'stop',
 'even',
 'tries',
 'agent',
 'battle',
 'journey',
 'parents',
 'comes',
 'men',
 'film',
 'decides',
 'year',
 'earth',
 'turns',
 'killer',
 'turn',
 'couple',
 'forces',
 'last',
 'live',
 'future',
 'left',
 'relationship',
 'dangerous',
 'yearold',
 'face',
 'whose',
 'also',
 'end',
 'little',
 'come',
 'another',
 'gang',
 'crime',
 'local',
 'escape',
 'around',
 'behind',
 'brother',
 'events',
 'beautiful',
 'series',
 'husband',
 'children',
 'may',
 'try',
 'real',
 'game',
 'prison',
 'sets',
 'away',
 'returns',
 'deadly',
 'us',
 'along',
 'dead',
 'money',
 'everything',
 'college',
 'crew',
 'island',
 'learns',
 'things',
 'trying',
 'leads',
 'search',
 'never',
 'big',
 'john',
 'four',
 'human',
 'trip',
 'drug',
 'place',
 'student',
 'wants',
 'dreams',
 'adventure',
 'plan',
 'detective',
 'revenge',
 'dark',
 'run',
 'child',
 'across',
 'force',
 'makes',
 'return',
 'put',
 'chance',
 'girlfriend',
 'sister',
 'days',
 'like',
 'power',
 'teenage',
 'case',
 'protect',
 'keep',
 'career',
 'sent',
 'known',
 'seems',
 'rescue',
 'begin',
 'car',
 'band',
 'called',
 'plans',
 'king',
 'determined',
 'race',
 'something',
 'could',
 'ever',
 'army',
 'long',
 'married',
 'dr',
 'shes',
 'women',
 'powerful',
 'decide',
 'meet',
 'every',
 'unexpected',
 'star',
 'upon',
 'starts',
 'bring',
 'survive',
 'criminal',
 'still',
 'lost',
 'jack',
 'start',
 'attempt',
 'paris',
 'childhood',
 'french',
 'government',
 'planet',
 'christmas',
 'business',
 'country',
 'change',
 'next',
 'accident',
 'friendship',
 'learn',
 'angeles',
 'suddenly',
 'village',
 'los',
 'strange',
 'quest',
 'girls',
 'good',
 'quickly',
 'based',
 'nothing',
 'working',
 'marriage',
 'later',
 'different',
 'violent',
 'land',
 'killed',
 'kill',
 'truth',
 'officer',
 'desperate',
 'great',
 'control',
 'company',
 'black',
 'cop',
 'kids',
 'history',
 'five',
 'finally',
 'summer',
 'party',
 'taken',
 'heart',
 'london',
 'wealthy',
 'show',
 'students',
 'leave',
 'boss',
 'following',
 'alien',
 'brothers',
 'arrives',
 'far',
 'whos',
 'moves',
 'everyone',
 'th',
 'legendary',
 'dream',
 'part',
 'personal',
 'without',
 'lead',
 'late',
 'ancient',
 'see',
 'music',
 'road',
 'british',
 'many',
 'head',
 'perfect',
 'romance',
 'well',
 'captain',
 'would',
 'mystery',
 'single',
 'alone',
 'struggles',
 'fate',
 'bond',
 'others',
 'ruthless',
 'fall',
 'struggle',
 'unlikely',
 'attempts',
 'follows',
 'works',
 'remote',
 'accidentally',
 'worlds',
 'missing',
 'taking',
 'move',
 'within',
 'body',
 'hope',
 'wedding',
 'including',
 'murdered',
 'going',
 'teacher',
 'leader',
 'destroy',
 'leaves',
 'france',
 'south',
 'use',
 'join',
 'movie',
 'reality',
 'trapped',
 'since',
 'forever',
 'attack',
 'plot',
 'fbi',
 'partner',
 'form',
 'found',
 'powers',
 'despite',
 'much',
 'encounter',
 'successful',
 'caught',
 'secrets',
 'serial',
 'threatens',
 'stay',
 'win',
 'prove',
 'making',
 'apartment',
 'killing',
 'travels',
 'ends',
 'frank',
 'enemy',
 'break',
 'doctor',
 'boyfriend',
 'investigate',
 'turned',
 'tells',
 'deal',
 'white',
 'realizes',
 'play',
 'sinister',
 'travel',
 'space',
 'inside',
 'deep',
 'hit',
 'america',
 'wrong',
 'james',
 'led',
 'professor',
 'century',
 'master',
 'owner',
 'military',
 'top',
 'special',
 'teenager',
 'camp',
 'terrifying',
 'getting',
 'right',
 'seemingly',
 'joins',
 'ii',
 'teen',
 'uncover',
 'fellow',
 'pair',
 'looking',
 'yet',
 'struggling',
 'always',
 'action',
 'middle',
 'know',
 'wild',
 'affair',
 'princess',
 'made',
 'mr',
 'though',
 'magical',
 'kidnapped',
 'writer',
 'survival',
 'guy',
 'identity',
 'community',
 'brings',
 'hero',
 'doesnt',
 'ship',
 'queen',
 'baby',
 'famous',
 'street',
 'humans',
 'eventually',
 'course',
 'embark',
 'soldiers',
 'free',
 'side',
 'boys',
 'bad',
 'bank',
 'tale',
 'becoming',
 'final',
 'david',
 'art',
 'brutal',
 'visit',
 'confront',
 'romantic',
 'england',
 'fighting',
 'hidden',
 'lawyer',
 'teams',
 'assassin',
 'fathers',
 'might',
 'law',
 'dog',
 'troubled',
 'older',
 'book',
 'international',
 'supernatural',
 'using',
 'female',
 'popular',
 'spirit',
 'epic',
 'existence',
 'seeks',
 'several',
 'united',
 'theyre',
 'eve',
 'involved',
 'track',
 'train',
 'vacation',
 'social',
 'needs',
 'peter',
 'leading',
 'ultimate',
 'embarks',
 'private',
 'cia',
 'finding',
 'paul',
 'anything',
 'knows',
 'ways',
 'entire',
 'heist',
 'members',
 'journalist',
 'name',
 'apart',
 'leaving',
 'enough',
 'puts',
 'younger',
 'daughters',
 'artist',
 'hunt',
 'justice',
 'faces',
 'prince',
 'rich',
 'test',
 'class',
 'cant',
 'age',
 'danger',
 'and',
 'sisters',
 'humanity',
 'streets',
 'states',
 'president',
 'changes',
 'alive',
 'trouble',
 'west',
 'sea',
 'reporter',
 'runs',
 'person',
 'path',
 'uses',
 'estranged',
 'rock',
 'want',
 'monster',
 'russian',
 'really',
 'hired',
 'rise',
 'among',
 'six',
 'lord',
 'elite',
 'hopes',
 'creatures',
 'sees',
 'better',
 'familys',
 'beloved',
 'hospital',
 'nightmare',
 'full',
 'scientist',
 'veteran',
 'holiday',
 'hotel',
 'experience',
 'sex',
 'characters',
 'hell',
 'nick',
 'encounters',
 'conspiracy',
 'give',
 'michael',
 'criminals',
 'eye',
 'society',
 'call',
 'rest',
 'realize',
 'eccentric',
 'alex',
 'increasingly',
 'able',
 'meanwhile',
 'tom',
 'grows',
 'seek',
 'stories',
 'ago',
 'killers',
 'solve',
 'close',
 'pregnant',
 'desert',
 'figure',
 'drawn',
 'believes',
 'escapes',
 'second',
 'steal',
 'hollywood',
 'means',
 'undercover',
 'magic',
 'de',
 'investigation',
 'notorious',
 'security',
 'prevent',
 'hands',
 'early',
 'discovery',
 'forest',
 'charlie',
 'given',
 'peace',
 'look',
 'threat',
 'corrupt',
 'ben',
 'video',
 'victims',
 'max',
 'growing',
 'instead',
 'political',
 'state',
 'adventures',
 'hometown',
 'universe',
 'violence',
 'believe',
 'target',
 'uncle',
 'latest',
 'abandoned',
 'california',
 'thing',
 'skills',
 'italy',
 'met',
 'park',
 'creature',
 'unexpectedly',
 'unknown',
 'care',
 'problems',
 'rival',
 'chaos',
 'member',
 'happens',
 'underground',
 'heroes',
 'dies',
 'ultimately',
 'cops',
 'english',
 'sam',
 'station',
 'follow',
 'greatest',
 'freedom',
 'crash',
 'birthday',
 'alice',
 'near',
 'lover',
 'heads',
 'act',
 'soldier',
 'line',
 'north',
 'arts',
 'hard',
 'tragic',
 'brilliant',
 'thief',
 'handsome',
 'sexual',
 'create',
 'stranger',
 'task',
 'spend',
 'isnt',
 'professional',
 'raised',
 'harry',
 'mind',
 'kingdom',
 'cat',
 'director',
 'beyond',
 'thinks',
 'stolen',
 'share',
 'murders',
 'coach',
 'neighbor',
 'loss',
 'consequences',
 'suspect',
 'italian',
 'room',
 'thought',
 'service',
 'tragedy',
 'ambitious',
 'receives',
 'experiences',
 'major',
 'fear',
 'texas',
 'question',
 'quiet',
 'assigned',
 'vampire',
 'capture',
 'driver',
 'stand',
 'german',
 'enters',
 'stranded',
 'loves',
 'witness',
 'george',
 'warrior',
 'building',
 'befriends',
 'outside',
 'la',
 'hunter',
 'martial',
 'singer',
 'key',
 'success',
 'mob',
 'haunted',
 'seven',
 'horror',
 'nuclear',
 'operation',
 'gold',
 'falling',
 'reunite',
 'isolated',
 'opportunity',
 'modern',
 'impossible',
 'weekend',
 'store',
 'recently',
 'tv',
 'trail',
 'safe',
 'agrees',
 'actually',
 'happy',
 'worst',
 'he',
 'appears',
 'due',
 'breaks',
 'san',
 'japanese',
 'ordinary',
 'suburban',
 'whole',
 'born',
 'residents',
 'lonely',
 'teenagers',
 'someone',
 'survivors',
 'fights',
 'sons',
 'easy',
 'cold',
 'million',
 'air',
 'global',
 'lands',
 'classic',
 'rome',
 'cannot',
 'comedy',
 'gone',
 'connection',
 'henry',
 'choice',
 'water',
 'terror',
 'problem',
 'seen',
 'kid',
 'gives',
 'situation',
 'losing',
 'east',
 'terrorist',
 'hiding',
 'causes',
 'plane',
 'chicago',
 'meeting',
 'estate',
 'retired',
 'general',
 'crisis',
 'need',
 'complicated',
 'worker',
 'clear',
 'nazi',
 'brought',
 'storm',
 'red',
 'obsessed',
 'worse',
 'mike',
 'farm',
 'memories',
 'neighborhood',
 'anna',
 'system',
 'pay',
 'process',
 'short',
 'running',
 'businessman',
 'dont',
 'public',
 'lies',
 'competition',
 'strangers',
 'richard',
 'program',
 'organization',
 'bizarre',
 'door',
 'charming',
 'coming',
 'destruction',
 'tour',
 'pilot',
 'open',
 'blood',
 'joe',
 'nearly',
 'massive',
 'terrible',
 'executive',
 'ring',
 'armed',
 'food',
 'duo',
 'dad',
 'secretly',
 'event',
 'memory',
 'shop',
 'innocent',
 'games',
 'phone',
 'sends',
 'monsters',
 'responsible',
 'arrive',
 'player',
 'mansion',
 'traveling',
 'soul',
 'football',
 'beauty',
 'rural',
 'mexico',
 'thieves',
 'fun',
 'fortune',
 'virus',
 'bloody',
 'ready',
 'johnny',
 'rule',
 'match',
 'looks',
 'complete',
 'infamous',
 'victim',
 'released',
 'vengeance',
 'avoid',
 'loses',
 'agents',
 'it',
 'proves',
 'times',
 'assignment',
 'center',
 'simple',
 'various',
 'dance',
 'defeat',
 'helps',
 'machine',
 'families',
 'training',
 'marry',
 'mark',
 'arrival',
 'fairy',
 'although',
 'possible',
 'hours',
 'computer',
 'cash',
 'results',
 'extraordinary',
 'unable',
 'mom',
 'mental',
 'enemies',
 'whether',
 'theres',
 'mans',
 'jim',
 'musical',
 'news',
 'newly',
 'lose',
 'legend',
 'held',
 'radio',
 'feels',
 'god',
 'sarah',
 'anyone',
 'thats',
 'fire',
 'underworld',
 'defend',
 'chief',
 'mothers',
 'hostage',
 'sense',
 'idea',
 'months',
 'robot',
 'squad',
 'fears',
 'beginning',
 'paths',
 'biggest',
 'demons',
 'fly',
 'royal',
 'presence',
 'empire',
 'involving',
 'evidence',
 'die',
 'animals',
 'dragon',
 'expert',
 'hand',
 'odds',
 'reluctantly',
 'suffering',
 'normal',
 'teens',
 'seeking',
 'dealer',
 'office',
 'woods',
 'upside',
 'present',
 'offers',
 'relationships',
 'club',
 'morning',
 'aspiring',
 'role',
 'turning',
 'recruits',
 'catch',
 'cause',
 'chinese',
 'hilarious',
 'compete',
 'green',
 'strikes',
 'nature',
 'support',
 'accused',
 'vicious',
 'wake',
 'manager',
 'destroyed',
 'risk',
 'awry',
 'partners',
 'civil',
 'champion',
 'happened',
 ...]

In [ ]:
import plotly.express as px
fig = px.scatter_3d(store[:100],x=0,y=1,z=2, color=y[:100])
fig.show()